version: "2.3"
services:
    milvus:
        runtime: nvidia
        restart: always
        image: milvusdb/milvus:0.5.0-d102119-ede20b
        # ports:
        #     - "0.0.0.0:19530:19530"
        volumes:
            - /tmp/milvus/db:/opt/milvus/db

    jaeger:
        restart: always
        image: jaegertracing/all-in-one:1.14
        ports:
            - "0.0.0.0:5775:5775/udp"
            - "0.0.0.0:16686:16686"
            - "0.0.0.0:9441:9441"
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411

    mishards:
        restart: always
        image: milvusdb/mishards:0.1.0-rc0
        ports:
            - "0.0.0.0:19530:19531"
            - "0.0.0.0:19532:19532"
        volumes:
            - /tmp/milvus/db:/tmp/milvus/db
            # - /tmp/mishards_env:/source/mishards/.env
        command: ["python", "mishards/main.py"]
        environment:
            FROM_EXAMPLE: 'true'
            DEBUG: 'true'
            SERVER_PORT: 19531
            WOSERVER: tcp://milvus:19530
            SD_STATIC_HOSTS: milvus
            TRACING_TYPE: jaeger
            TRACING_SERVICE_NAME: mishards-demo
            TRACING_REPORTING_HOST: jaeger
            TRACING_REPORTING_PORT: 5775

        depends_on:
            - milvus
            - jaeger
